monitor.alsa.rules = [
  {
    matches = [
      { node.name = "alsa_output.usb-MV-SILICON_fifine_Microphone_20190808-00.analog-stereo" }
    ]
    actions = {
      update-props = {
        node.description = "Fifine Mic (Output Jack)"
        node.nick        = "Fifine Mic"
        priority.driver  = 100
        priority.session = 100
      }
    }
  }
  {
    matches = [
     { node.name = "alsa_output.pci-0000_01_00.1.hdmi-stereo-extra2" }
     { node.name = "alsa_output.pci-0000_01_00.1.hdmi-stereo-extra5" }
    ]
    actions = {
      update-props = {
        node.nick         = "Monitor Bult-in Speaker"
        node.description  = "Monitor Speaker"
        audio.channel-mix = "mono"
        audio.channel     = 1
        priority.driver   = 200
        priority.session  = 200
      }
    }
  }
  {
    matches = [
      { node.name = "alsa_output.pci-0000_00_1f.3.analog-stereo" }
    ]
    actions = {
      update-props = {
        node.description  = "Headset (Analog P2)"
        node.nick         = "Headset"
        audio.channel-mix = "mono"
        audio.channel     = 1
        priority.driver   = 300
        priority.session  = 300
      }
    }
  }
]
