monitor.alsa.rules = [
  {
    matches = [
      { "node.name" = "alsa_input.pci-0000_00_1f.3.analog-stereo" }
      { "node.name" = "alsa_input.usb-Generic_AB13X_USB_Audio_20210926172016-00.mono-fallback" }
    ]
    actions = {
      update-props = {
        "node.disabled" = true
      }
    }
  }
  {
    matches = [
      { "node.name" = "alsa_input.usb-MV-SILICON_fifine_Microphone_20190808-00.analog-stereo" }
    ]
    actions = {
      update-props = {
        "node.description" = "Fifine USB Microphone"
        "node.nick"        = "Fifine Mic"
        "priority.driver"  = 100
        "priority.session" = 100
      }
    }
  }
]
