set default-fg                rgba(230,247,255,1)
set default-bg                rgba(10,11,20,1)

set completion-bg             rgba(21,23,34,1)
set completion-fg             rgba(230,247,255,1)
set completion-highlight-bg   rgba(255,59,107,1)
set completion-highlight-fg   rgba(10,11,20,1)
set completion-group-bg       rgba(10,11,20,1)
set completion-group-fg       rgba(0,245,255,1)

set statusbar-fg              rgba(230,247,255,1)
set statusbar-bg              rgba(10,11,20,1)
set inputbar-fg               rgba(230,247,255,1)
set inputbar-bg               rgba(10,11,20,1)

set notification-bg           rgba(10,11,20,1)
set notification-fg           rgba(230,247,255,1)
set notification-error-bg     rgba(10,11,20,1)
set notification-error-fg     rgba(255,59,107,1)
set notification-warning-bg   rgba(10,11,20,1)
set notification-warning-fg   rgba(252,238,9,1)

set recolor                   "true"
set recolor-lightcolor        rgba(10,11,20,1)
set recolor-darkcolor         rgba(230,247,255,1)

set index-fg                  rgba(230,247,255,1)
set index-bg                  rgba(10,11,20,1)
set index-active-fg           rgba(252,238,9,1)
set index-active-bg           rgba(21,23,34,1)

set render-loading-bg         rgba(10,11,20,1)
set render-loading-fg         rgba(230,247,255,1)

set highlight-color           rgba(255,59,107,0.3)
set highlight-fg              rgba(230,247,255,1)
set highlight-active-color    rgba(252,238,9,0.35)
