################### GENERAL ###################
legacy_layout=false
round_corners=10
background_alpha=0.8
background_color=1E1E2E
table_columns=3

################ PERFORMANCE #################

### Limit the application FPS. Comma-separated list of one or more FPS values (e.g. 0,30,60). 0 means unlimited (unless VSynced)
# fps_limit=60

################### VISUAL ###################

### GPU
gpu_stats
gpu_temp
gpu_core_clock
gpu_mem_temp
gpu_mem_clock
gpu_power
gpu_power_limit
gpu_text=GPU
gpu_color=A6E3A1
gpu_load_change
gpu_load_value=60,90
gpu_load_color=CDD6F4,FAB387,F38BA8
gpu_fan

### CPU
cpu_stats
cpu_temp
cpu_power
cpu_text=CPU
cpu_mhz
cpu_color=89B4FA
cpu_load_change
cpu_load_value=60,90
cpu_load_color=CDD6F4,FAB387,F38BA8

### Display the current CPU load & frequency for each core
core_load
core_load_change

### Display system vram / ram
vram
ram
ram_color=F5C2E7

### Display FPS and frametime
fps
fps_value=30,60
fps_color=B22222,FDFD09,39F900
fps_color_change
fps_color_change=F38BA8,F9E2AF,A6E3A1
fps_text=FPS
fps_metrics=avg,0.01
frametime
frametime_color=A6E3A1

throttling_status_graph

### Change the hud font size
font_size=24
text_color=CDD6F4
text_outline_color=313244
font_scale=1.0
no_small_font

### Disable / hide the hud by default
no_display

################ INTERACTION #################

### Change toggle keybinds for the hud & logging
toggle_hud=Shift_L+F12
reset_fps_metrics=Shift_L+F11
