#!/usr/bin/env bash

# Use neovim for vim if present.
[[ -x "$(command -v nvim)" ]] && alias vim="nvim" vimdiff="nvim -d"

# Easily edit local bin
bin() {
  choice="$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
  [[ -f "${HOME}/.local/bin/${choice}" ]] && ${EDITOR} "${HOME}/.local/bin/${choice}"
}

# Yazi Shell Wrapper
y() {
  local tmp
  local cwd
  tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
  yazi "$@" --cwd-file="${tmp}"
  IFS= read -r -d '' cwd < "${tmp}"
  [[ -n "${cwd}" ]] && [[ "${cwd}" != "${PWD}" ]] && builtin cd -- "${cwd}" || exit 1
  rm -f -- "${tmp}"
}

# Verbosity and settings that you pretty much just always are going to want.
alias :q='exit' \
  cp="cp -iv" \
  mv="mv -iv" \
  rm="rm -vI"

# Reduce verbosity of common commands
alias p='pacman' \
  sp='sudo pacman' \
  pi='sudo pacman --sync --refresh' \
  tmux='tmux -u ' \
  ft='xdg-mime query filetype' \
  wget='wget --hsts-file="${XDG_CONFIG_HOME}"/wget/wget-hsts' \
  sc='shellcheck -x -P SCRIPTDIR -f tty -o all' \
  sxiv='nsxiv' \
  trash='gio trash ' \
  e='${EDITOR}' \
  v='${EDITOR}' \
  z="zathura" \
  open="xdg-open"

# Refresh sudo when reused
alias sudo='sudo -v; sudo '

# Set dotfiles git-dir directory
alias config='/usr/bin/git --git-dir="${HOME}"/.local/share/BLAST/dotfiles --work-tree="${HOME}"'

# custom command to alert when command has finished execution
alias alert='notify-send --urgency=critical                                   \
    -a "Hey, your command has finished !"                                     \
    -i "$(if [[ "${?}" = 0 ]];then echo terminal || echo error; fi)"          \
    "$(history|tail -n1|sed -e '"'s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'"')"'

# Colorize commands when possible.
alias diff='diff --color=auto ' \
  ls='ls -alshv --group-directories-first --color=auto ' \
  dir='dir --color=auto ' \
  vdir='vdir --color=auto ' \
  ip='ip -color=auto ' \
  grep='grep --color=auto '

yt() {
  if [[ "${#}" -eq 0 ]] || [[ "${#}" -gt 2 ]]; then
    echo "Usage: yt [-t | --timestamps] youtube-link"
    echo "Use the '-t' flag to get the transcript with timestamps."
    return 1
  fi
  transcript_flag="--transcript"
  if [[ "${1}" = "-t" ]] || [[ "${1}" = "--timestamps" ]]; then
    transcript_flag="--transcript-with-timestamps"
    shift
  fi
  video_link="${1}"
  fabric -y "${video_link}" "${transcript_flag}"
}
