#!/usr/bin/env sh

# ==============================================================================
# LOGOUT
# ------------------------------------------------------------------------------
# This script is executed when a login shell exits.
#
# Its purpose is to perform cleanup tasks, temporary-file cleanup,
# agent shutdown, logout messages.
# ==============================================================================

[ -t 1 ] && clear
