#!/bin/sh

# shellcheck disable=SC2016

# region: XDG Base Directories
export XDG_CONFIG_HOME="${HOME}"/.config
export XDG_CACHE_HOME="${HOME}"/.local/cache
export XDG_DATA_HOME="${HOME}"/.local/share
export XDG_STATE_HOME="${HOME}"/.local/state
# regionend

# region: Default programs
export EDITOR="nvim"
# regionend

# region: $HOME Cleanup...
export XAUTHORITY="${XDG_RUNTIME_DIR}"/Xauthority
export XCOMPOSEFILE="${XDG_CONFIG_HOME}}"/X11/xcompose
[ -d "${XDG_CACHE_HOME}"/X11 ] || mkdir -p "${XDG_CACHE_HOME}"/X11
export XCOMPOSECACHE="${XDG_CACHE_HOME}"/X11/xcompose
[ -d "${XDG_CACHE_HOME}"/less ] || mkdir -p "${XDG_CACHE_HOME}"/less
export LESSHISTFILE="${XDG_CACHE_HOME}"/less/lesshst
export WGETRC="${XDG_CONFIG_HOME}"/wget/wgetrc
export INPUTRC="${XDG_CONFIG_HOME}"/shell/inputrc
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
export GNUPGHOME="${XDG_DATA_HOME}"/gnupg
export TMUX_TMPDIR="${XDG_RUNTIME_DIR}"
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME}/android"
[ -d "${XDG_CACHE_HOME}"/sqlite ] || mkdir -p "${XDG_CACHE_HOME}"/sqlite
export SQLITE_HISTORY="${XDG_CACHE_HOME}/sqlite/history"
export GTK2_RC_FILES="${XDG_CONFIG_HOME}/gtk-2.0/gtkrc-2.0"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="${XDG_CONFIG_HOME}"/java
export CARGO_HOME="${XDG_DATA_HOME}"/cargo
export GOPATH="${HOME}/.local/share/go"
export GOBIN="${GOPATH}/bin"
[ -d "${XDG_CACHE_HOME}"/go ] || mkdir -p "${XDG_CACHE_HOME}"/go
export GOMODCACHE="${XDG_CACHE_HOME}/go/mod"
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/nvim/init.lua" | source $MYVIMRC'
export NVM_DIR="${HOME}/.config/nvm"
export PNPM_HOME="${HOME}/.local/share/pnpm"
export GOPATH="${HOME}/.local/share/go"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}"/npm/npmrc
# regionend

# region: Other program settings
SUDO_PROMPT="$(tput setab 1 setaf 7 bold)[sudo]$(tput sgr0) $(tput setaf 6)password for$(tput sgr0) $(tput setaf 5)%p$(tput sgr0): "
export SUDO_PROMPT
export SUDO_ASKPASS="${HOME}/.local/bin/rofi-askpass"
export ROC_ENABLE_PRE_VEGA=1
export PIPEWIRE_LATENCY="128/48000" application
# regionend

# region: Paths

# Add `~/.local/bin` and all it's directories to $PATH
PATH="${PATH}":"$(find ~/.local/bin -type d | paste -sd ':' -)"
# Add path to GO Bin
PATH="${PATH}":"${GOBIN}":
# Add path to Java 8
PATH="${PATH}":/usr/local/lib/java/jdk1.8.0_202/bin/
# Add path to pnpm
PATH="${PATH}":"${HOME}"/.local/share/pnpm

export PATH
# regionend
