# region: Settings

# Configurations (global defaults)
set  -g  default-terminal   "screen-256color"
set  -ag terminal-overrides ",$TERM:Tc"
set  -g  default-shell      /bin/zsh

# session options
set  -g base-index       1
set  -g bell-action      any
set  -g escape-time      0
set  -g focus-events     on
set  -g history-limit    10000
set  -g renumber-windows on
set  -g repeat-time      1000
set  -g visual-bell      on
setw -g mouse            off
set  -g display-time     4000
set  -g status-interval  5

# window options
set  -g pane-base-index   1
setw -g mode-keys         vi
setw -g aggressive-resize on
# endregion

# region: Theme
# Status bar
set -g status-position top
set -g status-justify  left

set -g status-style "bg=default,fg=#cdd6f4,bright"
set -g status-left  ""
set -g status-right " #[fg=#9399b2,bright]#S [#W]"

# Window buttons
set -g window-status-separator      ""
set -g window-status-format         " ●"
set -g window-status-style          "fg=#585b70,nobold"
set -g window-status-current-format " ●"
set -g window-status-current-style  "#{?window_zoomed_flag,fg=#fab387,fg=#eba0ac,nobold}"
set -g window-status-bell-style     "fg=#cba6f7,nobold"

# Panes
set -g pane-border-lines        simple
set -g pane-border-style        "fg=#585b70,nobold"
set -g pane-active-border-style "fg=#eba0ac"

# Message
set -g message-style         "bg=default,fg=default,nobold"
set -g message-command-style "bg=#313244,fg=#f38ba8"

# Cursor
set -g cursor-style block
# regionend

# region: Keybindings

# Prefix
set -g prefix C-Space
unbind C-b; bind C-Space send-prefix

# Reload config file
bind r source-file ~/.config/tmux/tmux.conf

# Window
bind    - split-window    -v -c "#{pane_current_path}"
bind    | split-window    -h -c "#{pane_current_path}"
bind -r n next-window
bind -r p previous-window
bind    f resize-pane     -Z

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r Left  resize-pane -L 5
bind -r Up    resize-pane -U 5
bind -r Down  resize-pane -D 5
bind -r Right resize-pane -R 5

# copy mode (PREFIX + [) with vi bindings
bind -T copy-mode-vi v   send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y   send-keys -X copy-selection-and-cancel

# Commands
bind -r v run-shell "tmux neww tsesh"
# regionend
