# region: Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
# regionend

# region: Theme
set -g status-interval 10
set -g status-style "bg=#282c34,fg=#5fd7ff"
set -g message-style "bg=#282c34,fg=#ff00ff"
set -g message-command-style "bg=#282c34,fg=#ff00ff"
set -g pane-border-style "fg=#00d7af"
set -g pane-active-border-style "fg=#00d7af"
set -g status-left-length 60
set -g status-right-length 120
set -g status-left " #[fg=#5fd7ff,bg=#282c34][SESH: #S] #[fg=#585858]|"
set -g status-right "#[fg=#5fd7ff]#(free -h --giga | awk '/Mem:/ {print $3 \"/\" $2}') #[fg=#585858]| #[fg=#5fd7ff]#(date '+%d/%m/%Y %H:%M') "
setw -g window-status-format "#[fg=#585858] #I-#W"
setw -g window-status-current-format "#[fg=#5fd7ff,bold] #I#[fg=#585858]-#[fg=#5fd7ff]#[fg=#5fd7ff]#W"
setw -g mode-style "bg=#2c323c,fg=#00d7af"
set -g visual-bell on
set -g bell-action any
set -g status-justify left
set -g status-position bottom
set -g cursor-style block
# regionend

# region: Configurations
setw              -g  mouse              off
set               -g  default-terminal   "$TERM"
set-option        -g  focus-events       on
set-option        -ag terminal-overrides ",$TERM:Tc"
set-window-option -g  mode-keys          vi

# INDEX WINDOWS AT 1, NOT 0
set               -g base-index       1
set               -g pane-base-index  1
set-window-option -g pane-base-index  1
set-option        -g renumber-windows on
# regionend

# region: Bindings

# Reload config file
unbind r
bind   r source-file ~/.config/tmux/tmux.conf

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# copy mode (PREFIX + [) with vi bindings
bind-key -T copy-mode-vi v   send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y   send-keys -X copy-selection-and-cancel

bind -n M-Left  select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up    select-pane -U
bind -n M-Down  select-pane -D

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# OPEN PANES IN CURRENT DIRECTORY
bind '"' split-window -v -c "#{pane_current_path}"
bind %   split-window -h -c "#{pane_current_path}"

# PREFIX
unbind C-b
set    -g      prefix C-Space
bind   C-Space send-prefix
# regionend

run '~/.config/tmux/plugins/tpm/tpm'
