return {
  'mason-org/mason-lspconfig.nvim',
  dependencies = { 'mason-org/mason.nvim', 'neovim/nvim-lspconfig' },
  opts = {
    automatic_enable = false,
    ensure_installed = {
      'angularls',
      'bashls',
      'clangd',
      'cssls',
      'emmet_ls',
      'gopls',
      'graphql',
      'html',
      'jdtls',
      'jsonls',
      'lemminx',
      'lua_ls',
      'pyright',
      'ruff',
      'rust_analyzer',
      'sqls',
      'svelte',
      'tailwindcss',
      'vtsls',
      'yamlls',
    },
  },
}
