[mouse]
hide_when_typing = true
bindings = [
  { action = "ExpandSelection", mouse = "Right" },
  { action = "ExpandSelection", mouse = "Right",  mods = "Control"},
  { action = "PasteSelection",  mouse = "Middle", mode = "~Vi" }
]

[keyboard]
bindings = [
  { action = "Paste",                 key = "Paste" },
  { action = "Copy",                  key = "Copy" },
  { action = "ClearLogNotice",        key = "L",              mods = "Control" },
  { action = "ScrollPageUp",          key = "PageUp",         mods = "Shift",          mode = "~Alt" },
  { action = "ScrollPageDown",        key = "PageDown",       mods = "Shift",          mode = "~Alt" },
  { action = "ScrollToTop",           key = "Home",           mods = "Shift",          mode = "~Alt" },
  { action = "ScrollToBottom",        key = "End",            mods = "Shift",          mode = "~Alt" },
  { action = "SearchConfirm",         key = "Return",                                  mode = "Search|Vi" },
  { action = "SearchCancel",          key = "Escape",                                  mode = "Search" },
  { action = "SearchCancel",          key = "C",              mods = "Control",        mode = "Search" },
  { action = "SearchClear",           key = "U",              mods = "Control",        mode = "Search" },
  { action = "SearchDeleteWord",      key = "W",              mods = "Control",        mode = "Search" },
  { action = "SearchHistoryPrevious", key = "P",              mods = "Control",        mode = "Search" },
  { action = "SearchHistoryNext",     key = "N",              mods = "Control",        mode = "Search" },
  { action = "SearchHistoryPrevious", key = "Up",                                      mode = "Search" },
  { action = "SearchHistoryNext",     key = "Down",                                    mode = "Search" },
  { action = "SearchFocusNext",       key = "Return",                                  mode = "Search|~Vi" },
  { action = "SearchFocusPrevious",   key = "Return",         mods = "Shift",          mode = "Search|~Vi" },
  { action = "Paste",                 key = "V",              mods = "Control|Shift",  mode = "~Vi" },
  { action = "Copy",                  key = "C",              mods = "Control|Shift" },
  { action = "SearchForward",         key = "F",              mods = "Control|Shift",  mode = "~Search" },
  { action = "SearchBackward",        key = "B",              mods = "Control|Shift",  mode = "~Search" },
  { action = "ClearSelection",        key = "C",              mods = "Control|Shift",  mode = "Vi|~Search" },
  { action = "PasteSelection",        key = "Insert",         mods = "Shift"   },
  { action = "ResetFontSize",         key = "Key0",           mods = "Control" },
  { action = "IncreaseFontSize",      key = "Equals",         mods = "Control" },
  { action = "IncreaseFontSize",      key = "Plus",           mods = "Control" },
  { action = "IncreaseFontSize",      key = "NumpadAdd",      mods = "Control" },
  { action = "DecreaseFontSize",      key = "Minus",          mods = "Control" },
  { action = "DecreaseFontSize",      key = "NumpadSubtract", mods = "Control" },
  { action = "SpawnNewInstance",      key = "Return",         mods = "Control|Shift" },
  { chars  = "\f",                    key = "L",              mods = "Control",        mode = "~Vi|~Search" },
  { chars  = "\u001Bb",               key = "Left",           mods = "Control" },
  { chars  = "\u001Bf",               key = "Right",          mods = "Control" }
]
