#  _    _                  _                 _ 
# | |  | |                | |               | |
# | |__| |_   _ _ __  _ __| | __ _ _ __   __| |
# |  __  | | | | '_ \| '__| |/ _` | '_ \ / _` |
# | |  | | |_| | |_) | |  | | (_| | | | | (_| |
# |_|  |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#          __/ | |                             
#         |___/|_|                             

# Monitor
source = ~/.config/hypr/config/monitor.conf

# Environment
source = ~/.config/hypr/config/environment.conf

# Cursor
source = ~/.config/hypr/config/cursor.conf

# Keyboard
source = ~/.config/hypr/config/keyboard.conf

# Autostart
source = ~/.config/hypr/config/autostart.conf

# Load configuration files
source = ~/.config/hypr/config/decoration.conf
source = ~/.config/hypr/config/keybindings.conf
source = ~/.config/hypr/config/layout.conf
source = ~/.config/hypr/config/misc.conf
source = ~/.config/hypr/config/window.conf
source = ~/.config/hypr/config/windowrule.conf

# Animation
source = ~/.config/hypr/config/animations.conf

# MyLinuxForWork Configuration
# source = ~/.config/hypr/config/ml4w.conf

# Custom
# source = ~/.config/hypr/config/custom.conf
