#  _                      _     _ _      
# | |__  _   _ _ __  _ __(_) __| | | ___ 
# | '_ \| | | | '_ \| '__| |/ _` | |/ _ \
# | | | | |_| | |_) | |  | | (_| | |  __/
# |_| |_|\__, | .__/|_|  |_|\__,_|_|\___|
#        |___/|_|                        

general {
    lock_cmd         = pidof hyprlock || hyprlock # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session      # lock before suspend.
    after_sleep_cmd  = hyprctl dispatch dpms on   # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout    = 125.0                        # 2.5min
    on-timeout = hyprctl hyprsunset gamma 50  # Reduce gamma
    on-resume  = hyprctl hyprsunset gamma 100 # Restore gamma
}


listener {
    timeout    = 270      # 4.5min
    on-timeout = loginctl lock-session # Turn screen off
}

listener {
    timeout    = 300                       # 5min
    on-timeout = hyprctl dispatch dpms off # Turn screen off
    on-resume  = hyprctl dispatch dpms on  # Turn screen on
}

listener {
    timeout    = 600               # 10min
    on-timeout = systemctl suspend # suspend
}
