#  _                      _                 _ 
# | |__  _   _ _ __  _ __| | __ _ _ __   __| |
# | '_ \| | | | '_ \| '__| |/ _` | '_ \ / _` |
# | | | | |_| | |_) | |  | | (_| | | | | (_| |
# |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#        |___/|_|                             

source = $XDG_CONFIG_HOME/hypr/config/monitor.conf
source = $XDG_CONFIG_HOME/hypr/config/environment.conf
source = $XDG_CONFIG_HOME/hypr/config/autostart.conf
source = $XDG_CONFIG_HOME/hypr/config/animations.conf
source = $XDG_CONFIG_HOME/hypr/config/cursor.conf
source = $XDG_CONFIG_HOME/hypr/config/decoration.conf
source = $XDG_CONFIG_HOME/hypr/config/general.conf
source = $XDG_CONFIG_HOME/hypr/config/keyboard.conf
source = $XDG_CONFIG_HOME/hypr/config/layout.conf
source = $XDG_CONFIG_HOME/hypr/config/misc.conf
source = $XDG_CONFIG_HOME/hypr/config/windowrule.conf
source = $XDG_CONFIG_HOME/hypr/config/binds.conf
