# shellcheck shell=bash disable=SC1091

# IF NOT RUNNING INTERACTIVELY, DON'T DO ANYTHING
if [[ "${-}" != *i* ]]; then
    return
fi

# CUSTOMIZATION
shopt -s checkwinsize  # Line wrap on window resize.
shopt -s autocd  # Auto cd if command is a directory.
set -o noclobber  # Prevent overwrite of files.

# HISTORY CUSTOMIZATION
shopt -s histappend  # Append
HISTCONTROL=ignoredups  # Ignore duplicates
HISTSIZE=10000  # Maximum number os lines stored on memory
HISTFILESIZE=10000  # Maximum number os lines on file
HISTFILE="${XDG_CONFIG_HOME}"/bash/bash_history  # file location
PROMPT_COMMAND="${PROMPT_COMMAND:+${PROMPT_COMMAND}$'\n'} \
    history -a; history -c; history -r"  # Append every command

# SET A FANCY PROMPT (NON-COLOR, UNLESS WE KNOW WE "WANT" COLOR)
case "${TERM}" in
    xterm-color | *-256color)
        colorPrompt=yes
        ;;
    *) : ;;
esac

# forceColorPrompt=yes
if [[ -n "${forceColorPrompt}" ]]; then
    if [[ -x /usr/bin/tput ]] && tput setaf 1 >&/dev/null; then
        colorPrompt=yes
    else
        colorPrompt=
    fi
fi

# ALIASES
source "${XDG_CONFIG_HOME}"/bash/bash_aliases

# GIT
source "${XDG_CONFIG_HOME}"/git/git-prompt.sh
source "${XDG_CONFIG_HOME}"/git/git-completion.bash

# SET VARIABLE IDENTIFYING THE CHROOT YOU WORK IN
if [[ -z "${debianChroot:-}" && -r /etc/debian_chroot ]]; then
    debianChroot=$(cat /etc/debian_chroot)
fi

# CUSTOM PS1
if [[ "${colorPrompt}" = yes ]]; then
    PS1='\
\[\e[1;3;33m\]$(__git_ps1 "\n󰊢 %s")\[\e[0m\]\n\
${debianChroot:+($debianChroot)}\
\[\e[0;1;37m\]>_ \[\e[0m\]'
else
    PS1='$(__git_ps1 "שׂ %s")\n${debianChroot:+($debianChroot)}>_ '
fi

# MAKE LESS MORE FRIENDLY FOR NON-TEXT INPUT FILES, SEE LESSPIPE(1)
if [[ -x /usr/bin/lesspipe ]]; then
    eval "$(SHELL=/bin/sh lesspipe)"
fi

unset -v colorPrompt forceColorPrompt debianChroot
