# [colors.cursor]
# text = '#2e2e2d'
# cursor = '#ffffff'

[colors.primary]
background = '#000b1e'
foreground = '#37EBF3'

[colors.normal]
black = '#101010'
red = '#FF5151'
green = '#59FFA3'
yellow = '#FFD14F'
blue = '#00FFFF'
magenta = '#D351FF'
cyan = '#65FDFF'
white = '#D6D6D6'

[colors.bright]
black = '#272932'
red = '#FF0000'
green = '#5AFF5A'
yellow = '#FFD700'
blue = '#00FFFF'
magenta = '#CB1DCD'
cyan = '#37EBF3'
white = '#C1DEFF'
