#!/bin/bash

# Variable Definitions
userresources="${HOME}"/.Xresources
usermodmap="${HOME}"/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# MERGE IN DEFAULTS AND KEYMAPS
if [[ -f "${sysresources}"  ]]; then xrdb -merge "${sysresources}";  fi
if [[ -f "${sysmodmap}"     ]]; then xmodmap     "${sysmodmap}";     fi
if [[ -f "${userresources}" ]]; then xrdb -merge "${userresources}"; fi
if [[ -f "${usermodmap}"    ]]; then xmodmap     "${usermodmap}";    fi

# START SOME NICE PROGRAMS
if [[ -d /etc/X11/xinit/xinitrc.d ]] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        if [[ -x "${f}" ]]; then source "${f}"; fi
    done
    unset f
fi

# QUERY IF PROGRAM IS ALREADY RUNNING BEFORE EXECUTING.
function run() {
    if ! command pgrep -f "${1}"; then
        "${@}" &
    fi
}

# DESKTOP ENVIRONMENT | WINDOW MANAGER
session="${1}"
monitor="$(xrandr --listactivemonitors | awk 'NR==2{print $NF}')"
case "${session}" in
    qtile )
        xrandr --output "${monitor}" --mode 1920x1080 --rate 165 \
            || xrandr --output "${monitor}" --mode 1366x768      \
            || xrandr --output "${monitor}" --mode 1360x768      \
            || xrandr --output "${monitor}" --mode 1280x768      \
            || xrandr --output "${monitor}" --mode 1024x768      \
            || xrandr --output "${monitor}" --mode 800x600

        xset s off -dpms
        nitrogen --set-zoom-fill --random ~/Pictures/Wallpapers/
        run picom --experimental-backends \
            --config "${XDG_CONFIG_HOME}"/picom/picom.conf -b
        run dunst -conf/config "${XDG_CONFIG_HOME}"/dunst/dunstrc
        run flameshot
        run nm-applet
        run udiskie --tray
        run parcellite
        exec qtile start
        ;;
    *     ) exec "${1}" || printf "\nSession not found" ;;
esac

unset -f run
unset -v session monitor
