exec-once = "${XDG_CONFIG_HOME}"/BLAST/scripts/xdg.sh
exec-once = systemctl --user start hyprpolkitagent

exec-once = "${XDG_CONFIG_HOME}"/BLAST/scripts/waybar.sh
exec-once = udiskie --tray
exec-once = nm-applet

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = hypridle
exec-once = hyprpaper
exec-once = hyprsunset

exec-once = "${XDG_CONFIG_HOME}"/BLAST/scripts/wallpaper_changer.sh
