exec-once = "${XDG_CONFIG_HOME}"/BLAST/scripts/xdg.sh
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = dunst -conf/config "${XDG_CONFIG_HOME}"/dunst/dunstrc

exec-once = "${XDG_CONFIG_HOME}"/BLAST/scripts/waybar.sh
exec-once = udiskie --tray
exec-once = nm-applet

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = hyprpaper
exec-once = "${XDG_CONFIG_HOME}"/BLAST/scripts/wallpaper_changer.sh
