exec-once = $XDG_CONFIG_HOME/hypr/scripts/xdg.sh
exec-once = udiskie
exec-once = dunst -conf/config ~/.config/dunst/dunstrc
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
