decoration {
    dim_around = 0.4
    dim_inactive = false
    dim_special = 0.2
    dim_strength = 0.5
    rounding = 10
    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }
    blur {
        enabled = true
        size = 2
        passes = 1
    }
}
