$sumiInk0 = 16161dee
$autumnRed = c34043ee
$autumnGreen = 76946aee
$boatYellow2 = c0a36eee
$crystalBlue = 7e9cd8ee
$oniViolet = 957fb8ee
$waveAqua1 = 6a9589ee
$oldWhite = c8c093ee
$fujiGray = 727169ee
$lotusRed3 = e82424ee
$springGreen = 98bb6cee
$carpYellow = e6c384ee
$springBlue = 7fb4caee
$springViolet1 = 938aa9ee
$waveAqua2 = 7aa89fee
$lotusGray = dcd7baee
$sumiInk3 = 1f1f28ee
$waveBlue2 = 2d4f67ee

# background = $sumiInk3
# foreground = $lotusGray
# cursor-color = $oldWhite
# selection-background = $waveBlue2
# selection-foreground = $oldWhite

general {
    allow_tearing = false
    border_size = 2
    col.active_border = rgba($springViolet1) rgba($waveBlue2) 45deg
    col.inactive_border = rgba($sumiInk3)
    extend_border_grab_area = 15
    gaps_in = 3
    gaps_out = 8
    gaps_workspaces = 0
    hover_icon_on_border = false
    layout = dwindle
    no_border_on_floating = false
    no_focus_fallback = true
    resize_on_border = true
}
