windowrulev2 = tile,class:*(Brave-browser)$
windowrulev2 = float,class:(VirtualBox Machine)
windowrulev2 = float,class:(confirmreset)
windowrulev2 = float,class:(engrampa)
windowrulev2 = float,class:(firefox),title:(Picture-in-Picture)
windowrulev2 = float,class:(makebranch)
windowrulev2 = float,class:(maketag)
windowrulev2 = float,class:(ssh-askpass)
windowrulev2 = float,class:(thunar),title:(Confirm to replace files)
windowrulev2 = float,class:(thunar),title:(File Operation Progress)
windowrulev2 = float,title:(branchdialog)
windowrulev2 = float,title:(pinentry)
# windowrulev2 = forceinput, class:.*
windowrulev2 = opacity 0.8 0.8,class:^(Rofi)$
windowrulev2 = opacity 0.9 0.9,class:^(Alacritty)$
windowrulev2 = stayfocused, class:(Rofi)
windowrulev2 = suppressevent maximize, class:.*
# Smart gaps, aka: No gaps when only.
windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
windowrulev2 = rounding 0, floating:0, onworkspace:f[1]
