windowrule = tile,                   class:*(firefox)$
windowrule = tile,                   class:Nsxiv
windowrule = float,                  class:^(java|Java)$
windowrule = float,                  class:(VirtualBox Machine)
windowrule = float,                  class:(confirmreset)
windowrule = float,                  class:(engrampa)
windowrule = float,                  class:*(firefox), title:(Picture-in-Picture)
windowrule = float,                  class:(makebranch)
windowrule = float,                  class:(maketag)
windowrule = float,                  class:(ssh-askpass)
windowrule = float,                  class:(thunar),  title:(Confirm to replace files)
windowrule = float,                  class:(thunar),  title:(File Operation Progress)
windowrule = float,                  title:(branchdialog)
windowrule = float,                  title:(pinentry)
windowrule = float,                  class:org.ksnip.ksnip
windowrule = opacity 0.9 0.9,        class:(wezterm)$
windowrule = opacity 0.9 0.9,        class:com.mitchellh.ghostty
windowrule = opacity 0.9 0.9,        class:^(kitty)$
windowrule = stayfocused,            class:(Rofi)
windowrule = suppressevent maximize, class:.*

# Smart gaps, aka: No gaps when only.
# workspace = w[tv1],        gapsout:0,  gapsin:0
# workspace = f[1],          gapsout:0,  gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0,   floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0,   floating:0, onworkspace:f[1]
