general {
    allow_tearing = false
    border_size = 2
    col.active_border = rgba(ff8080ee)
    col.inactive_border = rgba(65151b00)
    extend_border_grab_area = 15
    gaps_in = 3
    gaps_out = 8
    gaps_workspaces = 0
    hover_icon_on_border = false
    layout = dwindle
    no_border_on_floating = false
    no_focus_fallback = true
    resize_on_border = true
}
